### ISSUE TITLE
fix README format

### ISSUE THREAD

**Issue by AliciaMstt** [ALBERTOPP/Tareas_BioinfRepro2019_AEPP#2]
Markdown format needs to be used properly:

* README titles are not showing properly. You need to add a space after `#` for they to work properly.

* Links are more useful when you use them to highlight a word (or words) with them, not only adding the link. For example [a link to gmail like this](www.gmail.com) is nicer than saying gmail [www.gmail.com]

**Comment by ALBERTOPP** [comment]
resolved :)
